"""empty message

Revision ID: 9399fd822fb8
Revises: 
Create Date: 2020-05-29 15:48:02.944403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9399fd822fb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Goal slug', sa.String(), nullable=True),
    sa.Column('Goal text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('request_lesson',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Phone', sa.String(), nullable=True),
    sa.Column('Goal', sa.String(), nullable=True),
    sa.Column('Timing', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('teachers',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('About', sa.String(), nullable=True),
    sa.Column('Rating', sa.Float(), nullable=True),
    sa.Column('Picture', sa.String(), nullable=True),
    sa.Column('Price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('booking',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Phone', sa.String(), nullable=True),
    sa.Column('Week Day', sa.String(), nullable=True),
    sa.Column('Timing', sa.String(), nullable=True),
    sa.Column('Teacher ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Teacher ID'], ['teachers.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('schedule',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Week Day', sa.String(), nullable=True),
    sa.Column('Timing', sa.String(), nullable=True),
    sa.Column('Teacher ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Teacher ID'], ['teachers.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('teacher_goals',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.ID'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.ID'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_goals')
    op.drop_table('schedule')
    op.drop_table('booking')
    op.drop_table('teachers')
    op.drop_table('request_lesson')
    op.drop_table('goals')
    # ### end Alembic commands ###
